### PR TITLE
Limit Response info dataset queries

### PR DESCRIPTION
**Pull request by noah-paige**
### Feature or Bugfix

- Refactor

### Detail
- Change Response Types for Dataset, Dashboard, and Shares Modules:
  - S3Datasets: `getDataset`, `getDatasetTables`, and `getDatasetStorageLocation` to only return Simplified Env / Org 
return types
  - ++ Redshift Datasets
  - ++ Dataset Shares

### Relates
- <URL or Ticket>

### Security
Please answer the questions below briefly where applicable, or write `N/A`. Based on
[OWASP 10](https://owasp.org/Top10/en/).

- Does this PR introduce or modify any input fields or queries - this includes
fetching data from storage outside the application (e.g. a database, an S3 bucket)?
  - Is the input sanitized?
  - What precautions are you taking before deserializing the data you consume?
  - Is injection prevented by parametrizing queries?
  - Have you ensured no `eval` or similar functions are used?
- Does this PR introduce any functionality or component that requires authorization?
  - How have you ensured it respects the existing AuthN/AuthZ mechanisms?
  - Are you logging failed auth attempts?
- Are you using or adding any cryptographic features?
  - Do you use a standard proven implementations?
  - Are the used keys controlled by the customer? Where are they stored?
- Are you introducing any new policies/roles/users?
  - Have you used the least-privilege principle? How?

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by noah-paige** [comment]
Testing Completed:

- [x] All Dataset Tabs Load += `getDataset` returns with correct information on FE
- [x] All Dataset Tabs Load += `getDatasetTables` returns with correct information on FE
- [x] All Dataset Tabs Load += `getDatasetStorageLocation` returns with correct information on FE
- [ ] All Dataset Tabs Load += `getRedshiftDataset` returns with correct information on FE
- [ ] All Dataset Tabs Load += `getRedshiftDatasetTable` returns with correct information on FE

**Comment by SofiaSazonova** [comment]
Error in query `ListDatasets` (/console/datasets) "Cannot query field 'organization' on type 'DatasetBase'."

**Comment by SofiaSazonova** [comment]
Is it necessary to change `Environment` => `SimplifiedEnvironment` also in queries?
```
ListDataPipelines
GetDataPipeline
ListOmicsRun
getSagemakerNotebook
ListSagemakerNotebooks
ListSagemakerStudioUsers
getSagemakerStudioUser
```

**Review by SofiaSazonova — CHANGES_REQUESTED** [review]
An error and a question

**Comment by SofiaSazonova** [comment]
Also, a comment: in dataset e.g. if we change name, label doesn't change (or it was a bug). Will it work the same for environments? If so, we risk to have confusing data displayed if use label instead of name

**Comment by noah-paige** [comment]
> Error in query `ListDatasets` (/console/datasets) `"Cannot query field 'organization' on type 'DatasetBase'."`

Good catch resolved now

**Comment by noah-paige** [comment]
> Also, a comment: in dataset e.g. if we change name, label doesn't change (or it was a bug). Will it work the same for environments? If so, we risk to have confusing data displayed if use label instead of name

This is outside of the scope of this PR yes? I actually think we should prevent updates to label for datasets or envs or any resources in dataall unless we are certain they have no impact on provisioned resources via CDK

**Review by SofiaSazonova — APPROVED** [review]

**Pull request merged**
