### PR TITLE
Add search (Autocomplete) in miscellaneous dropdowns

### PR DESCRIPTION
**Pull request by dlpzx**
### Feature or Bugfix
- Feature

### Detail
Autocomplete for environments and teams in the following frontend views as requested in #1012. In this case the views required custom dropdowns. 

❗ I used `noOptionsText` whenever it was necessary instead of checking groupOptions lenght >0
- [x] DatasetEditForm.js -> ❗ I kept the stewards field as `freesolo` - what that means is that users CAN specify options that are not on the list. I would like the reviewer to confirm this is what we want. At the end stewardship is a delegation of permissions, it makes sense that delegation happens to other teams. Also changed DatasetCreateForm
- [X] RequestDashboardAccessModal.js - already implemented, minor changes
- [X] EnvironmentTeamInviteForm.js - already implemented, minor changes. -> Kept `freesolo` because invited teams might not be the user teams. Same reason why there is no check for groupOptions == 0, if there are no options there is still the free text option.
- [X] EnvironmentRoleAddForm.js
- [X] NetworkCreateModal.js 

### Relates
- #1012 

### Security
Please answer the questions below briefly where applicable, or write `N/A`. Based on
[OWASP 10](https://owasp.org/Top10/en/).

- Does this PR introduce or modify any input fields or queries - this includes
fetching data from storage outside the application (e.g. a database, an S3 bucket)?
  - Is the input sanitized?
  - What precautions are you taking before deserializing the data you consume?
  - Is injection prevented by parametrizing queries?
  - Have you ensured no `eval` or similar functions are used?
- Does this PR introduce any functionality or component that requires authorization?
  - How have you ensured it respects the existing AuthN/AuthZ mechanisms?
  - Are you logging failed auth attempts?
- Are you using or adding any cryptographic features?
  - Do you use a standard proven implementations?
  - Are the used keys controlled by the customer? Where are they stored?
- Are you introducing any new policies/roles/users?
  - Have you used the least-privilege principle? How?

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by noah-paige** [comment]
for `EnvironmentRoleAddForm` and `NetworkCreateModal` I can type out any group name and submit the form even if it is not in the options

- removing the lines `// onChange={handleChange}` and changing `inputValue={values.groupUri}` to `value={values.groupUri}` seemed to resolve

- this may be occuring in a number of places may want to check
    - update: tested with DatasetCreateForm and also could type in random string for Team without it being discarded when clicking out
    - commenting out `inputValue={values.SamlAdminGroupName}` seemed to resolve (I believe we added this to help with text clearing when clear env but it seems like text is still clearing appropriately)

**Comment by noah-paige** [comment]
Instead of `freeSolo` would it make more sense for the groupOptions for `stewards` to be the groups in the Environment

and for `EnvironmentTeamInvite` the options for group be the OrganizationGroup members?  

`freeSolo` can be fine too but should likely have some validation whether a group is valid on the backend in that case (if not already there)

**Comment by dlpzx** [comment]
To track this issue on the filtered listGroups queries I opened a separate [issue](https://github.com/data-dot-all/dataall/issues/1370)

**Comment by dlpzx** [comment]
Hi @noah-paige, I have fixed the glitch in the NetworkCreate view and in the inviteRole form. For the views where we have an environment selector and a group selector is a little more difficult.
- if we use inputValue, the group current text does not get cleared out
- if we use value, the group selected does not get cleared out after another environment is selected
I think we could consider it as a feature out of the scope of this PR

**Review by noah-paige — APPROVED** [review]
lgtm

**Pull request merged**
