### PR TITLE
Add encryption and tag immutability to ECR repository

### PR DESCRIPTION
**Pull request by mourya-33**
### Feature or Bugfix
- Bugfix

### Detail
- Currently the ecr repository created do not have encryption and tag immutability enabled which is identified by checkov scans. This fix is to enable both.

### Relates
[- <URL or Ticket>](https://github.com/data-dot-all/dataall/issues/1200)

### Security
Please answer the questions below briefly where applicable, or write `N/A`. Based on
[OWASP 10](https://owasp.org/Top10/en/).

- Does this PR introduce or modify any input fields or queries - this includes
N/A
  - Is the input sanitized? N/A
  - What precautions are you taking before deserializing the data you consume? N/A
  - Is injection prevented by parametrizing queries? N/A
  - Have you ensured no `eval` or similar functions are used? N/A
- Does this PR introduce any functionality or component that requires authorization? N/A
  - How have you ensured it respects the existing AuthN/AuthZ mechanisms? N/A
  - Are you logging failed auth attempts? N/A
- Are you using or adding any cryptographic features? N/A
  - Do you use a standard proven implementations? N/A
  - Are the used keys controlled by the customer? Where are they stored? No. This is with default encryption
- Are you introducing any new policies/roles/users? N/A
  - Have you used the least-privilege principle? How? N/A

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by dlpzx** [comment]
Looks good! I am doing a quick test and I will merge. Thank you so much for the contribution @mourya-33 :)

**Review by dlpzx — CHANGES_REQUESTED** [review]
Hi @mourya-33, I have tested the PR on a real AWS deployment and it fails to update the ECR repository in the ECR stage of the CICD pipeline. The stack `<resource_prefix>-ecr-stage-<git_branch>-ecr-stack` in CloudFormation fails with the following message `CloudFormation cannot update a stack when a custom-named resource requires replacing. Rename <resource_prefix>-<git_branch>-repository and update the stack again.`

I have just pushed a quick test that modifies the ECR repository name to `repository_name = f"{self.resource_prefix}-{target_env['envname']}-ecr-repository"`. I'll keep you posted :) 


UPDATE: when changing the repository name the CICD pipeline succeeds and re-creates a new ECR repo with the correct encryption and tag immutability settings. The old repository is NOT deleted, so customers can still look up info about old docker images... and delete whenever.

**Comment by mourya-33** [comment]
Thanks @dlpzx . I will test this out on my end as well. Since i went with new deployment i did not notice this on my deployment.

**Comment by mourya-33** [comment]
The rename works @dlpzx . I pushed the change  in pipeline.py to the same branch to rename the repo

**Review by SofiaSazonova — APPROVED** [review]

**Review by SofiaSazonova — APPROVED** [review]

**Review by dlpzx — APPROVED** [review]

**Pull request merged**
