### PR TITLE
applying boto3==1.34.35 in DeployFrontend action

### PR DESCRIPTION
**Pull request by anandsumit2000**
### Feature or Bugfix

- Bugfix
- Refactoring

### Detail
- Fix towards "Pipeline Failure: DeployFrontEnd Stage - cannot import name 'is_s3express_bucket' from 'botocore.utils'"
   - Observed aforementioned error lately.
   -  Explicitly added s3transfer==0.8.0 in DeployFrontend stage to fulfil this deficiency.
      - Build  and Deploy successsful and Pipeline finished successfully.
   - Analysis of CodeBuild logs deduced a conclusion that irrespective of defining boto3==1.20.50 , botocore==1.34.39 was being pulled. However current version of botocore is 1.34.39. Logs claim that AWS CLI does not support 1.34.39. (Apologies, I forgot to pull logs).
      - So applied boto3==1.34.35 as a result stage pulled botocore `botocore<1.35.0,>=1.34.35 in /root/.pyenv/versions/3.9.17/lib/python3.9/site-packages (from boto3==1.34.35) (1.34.35)` 
      - No new dependency conflicts discovered after this.

- Hence Recommending the said version revision to boto3.
 
### Relates
- #1051 

### Security
Please answer the questions below briefly where applicable, or write `N/A`. Based on
[OWASP 10](https://owasp.org/Top10/en/).

N/A

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by anandsumit2000** [comment]
Yes thats exactly the tldr of my PR.

**Comment by dlpzx** [comment]
Related issue opened in the boto repository: https://github.com/boto/botocore/issues/3105

**Comment by dlpzx** [comment]
Hi @anandsumit2000, we read your PR sorry if it seemed otherwise. It is great when PRs are well described. I just wanted to point out that your conclusion from the CodeBuild logs analysis is the same one as the one provided by the AWS support team and it seems to be affecting Python 3.9 runtimes only. I tested data.all v2.2 that uses Amazon Linux 2 v5 and the pipeline runs successfully because the Python runtime is 3.11. We will do more testing on the last version and get back to you if the PR needs changes

**Comment by dlpzx** [comment]
Hi @anandsumit2000, I have added the upgraded version of boto3 to all other CodeBuild stages in `pipeline.py`. We tested these changes in some of our deployments so the PR is approved and ready to be merged!
Thanks for the troubleshooting, the logging and for opening a PR.

As next steps, we should also upgrade the version of boto3 used in the compute components of the backend and optimize the way we are managing boto versions: hardcoded in 4 different places + requirements.txt in diffferent places of the project.

**Review by dlpzx — APPROVED** [review]
Tested

**Pull request merged**
