### PR TITLE
Add permission checks to markNotificationAsRead + deleteNotification

### PR DESCRIPTION
**Pull request by noah-paige**
### Feature or Bugfix

- Bugfix

### Detail
- Add check to ensure user is a recipient of a Notification before allowing to mark as read or delete

### Security
Please answer the questions below briefly where applicable, or write `N/A`. Based on
[OWASP 10](https://owasp.org/Top10/en/).

- Does this PR introduce or modify any input fields or queries - this includes
fetching data from storage outside the application (e.g. a database, an S3 bucket)?
  - Is the input sanitized?
  - What precautions are you taking before deserializing the data you consume?
  - Is injection prevented by parametrizing queries?
  - Have you ensured no `eval` or similar functions are used?
- Does this PR introduce any functionality or component that requires authorization?
  - How have you ensured it respects the existing AuthN/AuthZ mechanisms?
  - Are you logging failed auth attempts?
- Are you using or adding any cryptographic features?
  - Do you use a standard proven implementations?
  - Are the used keys controlled by the customer? Where are they stored?
- Are you introducing any new policies/roles/users?
  - Have you used the least-privilege principle? How?

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by noah-paige** [comment]
Tested this PR:

- [x] Recipient can `markNotificationAsRead`
- [x] Recipient can `deleteNotification`
- [x] (Tested Programmatically) Non-recipient Unauthroized to `markNotificationAsRead` or `deleteNotification` with following error:
```
An error occurred (UnauthorizedOperation) when calling UPDATE NOTIFICATION operation: User USERNAME is not the recipient user/group of the notification URI
```

**Comment by SofiaSazonova** [comment]
General thoughts: Usually we have access checks in service levels. I think it makes more sense

**Comment by noah-paige** [comment]
> General thoughts: Usually we have access checks in service levels. I think it makes more sense

you are correct - currently Notification module fails to follow that structure. Can we keep this PR as is focused on the fix in auth restrictions

I will add the NotificationService class and additional changes as part of https://github.com/data-dot-all/dataall/pull/1597 - the PR where we add notification integration tests and also we remove some unused GraphQL Ops from notification module (already handling some refactoring may be best to lump it all in that PR?)

**Comment by SofiaSazonova** [comment]
Yes, we can put it as a refactoring issue in backlog

**Review by SofiaSazonova — APPROVED** [review]

**Pull request merged**
