### PR TITLE
Add search (Autocomplete) in group dropdown for useGroups

### PR DESCRIPTION
**Pull request by dlpzx**
### Feature or Bugfix
- Feature

### Detail
Autocomplete for environments and teams in the following frontend views as requested in 1012.  In this PR the changes apply to those views that use `useGroups` to define the `groupOptions`
- [x] WorksheetCreateForm.js
- [x] EnvironmentCreateForm.js
- [x] OrganizationCreateForm.js
- [x] GlossaryCreateForm.js

❗ In the EnvironmentCreateForm we might need to filter out the list of groups provided. At the moment users can select any group that they belong to. With the changes done by @SofiaSazonova in #1306 I think we need to review if that is still appropriate. Do you think we should open a new PR for this change?

### Relates
- #1012 

### Security
Please answer the questions below briefly where applicable, or write `N/A`. Based on
[OWASP 10](https://owasp.org/Top10/en/).

- Does this PR introduce or modify any input fields or queries - this includes
fetching data from storage outside the application (e.g. a database, an S3 bucket)?
  - Is the input sanitized?
  - What precautions are you taking before deserializing the data you consume?
  - Is injection prevented by parametrizing queries?
  - Have you ensured no `eval` or similar functions are used?
- Does this PR introduce any functionality or component that requires authorization?
  - How have you ensured it respects the existing AuthN/AuthZ mechanisms?
  - Are you logging failed auth attempts?
- Are you using or adding any cryptographic features?
  - Do you use a standard proven implementations?
  - Are the used keys controlled by the customer? Where are they stored?
- Are you introducing any new policies/roles/users?
  - Have you used the least-privilege principle? How?

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by dlpzx** [comment]
## Testing:
- [X] Create Worksheet, correct input is passed
- [X] Create Worksheet, list groups, remove group and select another group
- [X] Create Environment, correct input is passed
- [X] Create Organization, correct input is passed
- [X] Create Glossary, correct input is passed


https://github.com/data-dot-all/dataall/assets/71252798/a2f099c0-c1ca-48b6-b15d-13f6c6610c2e

**Comment by SofiaSazonova** [comment]
@dlpzx 
About filter for groups. I thinks, It's more appropriate to list only groups, that are valid for this case: 
1. user belongs to this group
2. group is invited into org

Same holds for the invitation into environment: only groups invited into Org, can be invited into Env.

But on the other hand in can lead to a confusion, when user can't understand, why the target group is not listed. 
That's why I didn't touch this question in #1147

**Review by noah-paige — APPROVED** [review]
Changes look good and tested locally - approving

Agree we probably want to filter groups for Env Create Form but think this PR focus is only on Autocomplete component and meets that requirement

Feel free to create new PR or can re-request review on this after adding group filter if you want - but I think we are good to merge this as is and pick up that task separately

**Comment by dlpzx** [comment]
To track this issue on the filtered listGroups queries I opened a separate [issue](https://github.com/data-dot-all/dataall/issues/1370)

**Pull request merged**
