### PR TITLE
Fix Alembic Migration: has table checks

### PR DESCRIPTION
**Pull request by noah-paige**
### Feature or Bugfix

- Bugfix

### Detail
- Fix `has_table()` check to ensure dropping the tables if the exists as part of alembic migration upgrade 

### Relates
- https://github.com/data-dot-all/dataall/issues/1165

### Security
Please answer the questions below briefly where applicable, or write `N/A`. Based on
[OWASP 10](https://owasp.org/Top10/en/).

- Does this PR introduce or modify any input fields or queries - this includes
fetching data from storage outside the application (e.g. a database, an S3 bucket)? No
  - Is the input sanitized? N/A
  - What precautions are you taking before deserializing the data you consume? N/A
  - Is injection prevented by parametrizing queries? N/A
  - Have you ensured no `eval` or similar functions are used? N/A
- Does this PR introduce any functionality or component that requires authorization? No
  - How have you ensured it respects the existing AuthN/AuthZ mechanisms? N/A
  - Are you logging failed auth attempts? N/A
- Are you using or adding any cryptographic features? No
  - Do you use a standard proven implementations? N/A
  - Are the used keys controlled by the customer? Where are they stored? N/A
- Are you introducing any new policies/roles/users? No
  - Have you used the least-privilege principle? How? N/A

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by SofiaSazonova** [comment]
1. **Check passed:** All 'extra' tables are not created after 'make upgrade-db' of the clean DB
2. **Problem**. `make generate-migrations` creates a non empty migration. It means, smth was not tracked by our migrations, so maybe, we have to create another migration script.
 @dlpzx  have a look please

```
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset_lock', 'isLocked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset_lock', 'isLocked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
```

**Comment by SofiaSazonova** [comment]
@noah-paige good with me

**Comment by noah-paige** [comment]
> @noah-paige good with me

Should be fixed now

**Comment by SofiaSazonova** [comment]
Could you please add it as a new migration? 
E.g. customer may want to upgrade their current DB (without dropping) and then create their own migrations. 
Changes in past migrations won't help here(

**Comment by noah-paige** [comment]
> Could you please add it as a new migration? E.g. customer may want to upgrade their current DB (without dropping) and then create their own migrations. Changes in past migrations won't help here(

For the has table fix it is only an issue on fresh deployments right? For existing data.all deployments that then run that script it should be fine

For the dataset lock we aren't changing the DB or the way we create the `dataset_locks` table - instead we are changing the model class object for `DatasetLock()` so I think it should be fine here right?

**Comment by SofiaSazonova** [comment]
Hm, I see. Ok, then it should be fine.

**Review by SofiaSazonova — APPROVED** [review]

**Pull request merged**
