### PR TITLE
Fix/userguide dockerfile

### PR DESCRIPTION
**Pull request by dlpzx**
### Feature or Bugfix
- Bugfix

### Detail
- view #1087 

### Relates
- <URL or Ticket>

### Security
Please answer the questions below briefly where applicable, or write `N/A`. Based on
[OWASP 10](https://owasp.org/Top10/en/).

- Does this PR introduce or modify any input fields or queries - this includes
fetching data from storage outside the application (e.g. a database, an S3 bucket)?
  - Is the input sanitized?
  - What precautions are you taking before deserializing the data you consume?
  - Is injection prevented by parametrizing queries?
  - Have you ensured no `eval` or similar functions are used?
- Does this PR introduce any functionality or component that requires authorization?
  - How have you ensured it respects the existing AuthN/AuthZ mechanisms?
  - Are you logging failed auth attempts?
- Are you using or adding any cryptographic features?
  - Do you use a standard proven implementations?
  - Are the used keys controlled by the customer? Where are they stored?
- Are you introducing any new policies/roles/users?
  - Have you used the least-privilege principle? How?

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by dlpzx** [comment]
Hi @noah-paige I just finished the testing, it worked:
image

**Comment by noah-paige** [comment]
@dlpzx - pushed one update to give docker user some additional permissions to files needed by nginx, was having some issues on the next step when deploying ALBFrontendStack without adding the changes

**Comment by dlpzx** [comment]
I confirm the errors in the Albfront stage. I am now deploying the fix in my AWS account. Once it succeeds we can approve the PR

**Review by noah-paige — APPROVED** [review]
Tested in a VPC Facing AWS Deployment and able to acess userguide as expected

Approving

**Comment by dlpzx** [comment]
Tested in AWS again in fresh scenario, merging

**Pull request merged**
