### PR TITLE
[Gh 1570] feature flag for table metrics

### PR DESCRIPTION
**Pull request by TejasRGitHub**
### Feature or Bugfix
- Feature

### Detail

Using existing functions like is_feature_enabled to enabled / disable use of metrics and associated profiling jobs. 

### Relates

- https://github.com/data-dot-all/dataall/issues/1570

### Security
Please answer the questions below briefly where applicable, or write `N/A`. Based on
[OWASP 10](https://owasp.org/Top10/en/).

- Does this PR introduce or modify any input fields or queries - this includes
fetching data from storage outside the application (e.g. a database, an S3 bucket)? N/A
  - Is the input sanitized? 
  - What precautions are you taking before deserializing the data you consume?
  - Is injection prevented by parametrizing queries?
  - Have you ensured no `eval` or similar functions are used?
- Does this PR introduce any functionality or component that requires authorization? N/A
  - How have you ensured it respects the existing AuthN/AuthZ mechanisms?
  - Are you logging failed auth attempts?
- Are you using or adding any cryptographic features? No
  - Do you use a standard proven implementations?
  - Are the used keys controlled by the customer? Where are they stored?
- Are you introducing any new policies/roles/users? No
  - Have you used the least-privilege principle? How?

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by TejasRGitHub** [comment]
@dlpzx , @noah-paige , can you please take look at this PR. It is to disable/enable the metrics for dataset tables - https://github.com/data-dot-all/dataall/issues/1570

**Review by dlpzx — APPROVED** [review]
Looks good!

**Comment by dlpzx** [comment]
@TejasRGitHub there are some conflicts to resolve, but overall the feature looks good

**Comment by TejasRGitHub** [comment]
@dlpzx , updated branch to resolve merge conflicts in config.json. Thanks for reviewing and approving

**Pull request merged**
