### PR TITLE
Updating overly permissive policies tagged by checkov for environment role using least privilege principles

### PR DESCRIPTION
**Pull request by mourya-33**
### Feature or Bugfix
- Bugfix

### Detail
This PR is to restrict the overly permissive permissions in the environment role IAM policies that are tagged as FAILURES by checkov. Instead of using Get* and List* we specify the actions and type of resources granted. 

In addition, this PR uses KMS keys to encrypt the custom resources Lambdas in the S3 datasets module

### Relates
- https://github.com/data-dot-all/dataall/issues/1524

### Security
Please answer the questions below briefly where applicable, or write `N/A`. Based on
[OWASP 10](https://owasp.org/Top10/en/).

- Does this PR introduce or modify any input fields or queries - this includes
fetching data from storage outside the application (e.g. a database, an S3 bucket)?
  - Is the input sanitized? N/A
  - What precautions are you taking before deserializing the data you consume? N/A
  - Is injection prevented by parametrizing queries? N/A
  - Have you ensured no `eval` or similar functions are used? N/A
- Does this PR introduce any functionality or component that requires authorization? N/A
  - How have you ensured it respects the existing AuthN/AuthZ mechanisms? N/A
  - Are you logging failed auth attempts? N/A
- Are you using or adding any cryptographic features? N/A
  - Do you use a standard proven implementations? N/A
  - Are the used keys controlled by the customer? Where are they stored? N/A
- Are you introducing any new policies/roles/users? N/A
  - Have you used the least-privilege principle? How? Restricting overly permissive permissions to the required resources / principle only.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by dlpzx** [comment]
Hi @mourya-33, thanks for the PR! The changes look good! My only concern with this type of changes are the IAM service quota limitations. Could you add how this PR has been tested? We need to make sure that if all modules are enabled the environment team roles can still be created.

**Comment by mourya-33** [comment]
sure @dlpzx i will add all the modules and test and update it here.

**Comment by mourya-33** [comment]
so far i have tested the following @dlpzx. I will continue with testing the deletions as well and dataset imports. 

1. Linked environments
2. Enabled Sagemaker features
3. Created Datasets

**Comment by dlpzx** [comment]
Hi @mourya-33, with all the modules enabled, how many IAM managed policies are attached to the team environment roles?
Thank you for the PR, it is looking good :)

**Comment by mourya-33** [comment]
Tested all the deletes as well @dlpzx . I will re run with a new environment and reply shortly on the number of policies that are attached to the team environment.

**Comment by mourya-33** [comment]
@dlpzx there are 8 policies that are attached to env role once all modules are enabled.

**Comment by mourya-33** [comment]
I am modifying a few Glue/LF lambda functions where the env variables can be encrypted. I will add those changes to this PR as well @dlpzx

**Comment by mourya-33** [comment]
@dlpzx added the lambda encryption for all custom lambdas for glue/lf for the environment role. Tested the link environment with all modules enabled. Could you also test at your end approve if everything looks good?

**Review by dlpzx — APPROVED** [review]
lgtm

**Pull request merged**
